name: CI-CD

on: push

jobs:
  CI:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip' 

      - name: Install Packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2
          role-duration-seconds: 1200
          mask-aws-account-id: true

      - name: DVC Pull
        run: |
          pip install dvc[s3]
          dvc pull

      - name: Run Application
        run: |
          nohup streamlit run app.py --server.port 8000 &
          sleep 30 

      - name: Test App
        run: |
          pytest test_app.py
      
      - name: Stop Streamlit app
        run: |
          pkill -f "streamlit run"

      # Zip the required files
      - name: Zip files for deployment
        if: success()
        run: |
          zip -r deployment.zip appspec.yml deploy/scripts/install_dependencies.sh deploy/scripts/start_docker.sh

      # Upload the ZIP file to S3
      - name: Upload ZIP to S3
        if: success()
        run: |
          aws s3 cp deployment.zip s3://hybridrecsysdeploymentbucket/deployment.zip

      # Deploy to AWS CodeDeploy
      - name: Deploy to AWS CodeDeploy
        if: success()
        run: |
          aws deploy create-deployment \
          --application-name hybridrecommendersystem \
          --deployment-config-name CodeDeployDefault.AllAtOnce \
          --deployment-group-name hybridrecsysdeploymentgroup \
          --s3-location bucket=hybridrecsysdeploymentbucket,key=deployment.zip,bundleType=zip \
          --file-exists-behavior OVERWRITE \
          --region ap-southeast-2